substitutions:
  _REGION: us-east1
  _SERVICE_NAME: speed-proxy
  _ALLOWED_ORIGIN: https://speed.measurementlab.net
  _TOKEN_EXCHANGE_URL: https://auth.mlab-sandbox.measurementlab.net/v0/token/integration

steps:
  # 1. Build the container image
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/m-lab/${_SERVICE_NAME}:$BUILD_ID", "-t", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/m-lab/${_SERVICE_NAME}:latest", "."]

  # 2. Push to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args: ["push", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/m-lab/${_SERVICE_NAME}:${BUILD_ID}"]
    waitFor: ["Build"]

  # 3. Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: Deploy
    entrypoint: gcloud
    args: [
      "run", "deploy", "${_SERVICE_NAME}",
      "--image", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/m-lab/${_SERVICE_NAME}:$BUILD_ID",
      "--platform", "managed",
      "--region", "${_REGION}",
      "--allow-unauthenticated",
      "--set-secrets=API_KEY=speed-proxy-api-key:latest",
      "--set-env-vars=TOKEN_EXCHANGE_URL=${_TOKEN_EXCHANGE_URL},ALLOWED_ORIGIN=${_ALLOWED_ORIGIN}",
      "--memory=256Mi",
      "--cpu=1",
      "--project=${PROJECT_ID}"
    ]
    waitFor: ["Push"]

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/m-lab/${_SERVICE_NAME}:$BUILD_ID"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/m-lab/${_SERVICE_NAME}:latest"
